### ISSUE TITLE
Nikon nef support

### ISSUE THREAD

**Issue by antasimak** [Aries85/LightZone#114]
HI all of you,
I am a newcomer not that familiar with the LZN. I have tried to edit nef fotos from my NIKON D90, but  the s/w pompts "Urecognized image format - unsupported camera

Have I made something wrong?

**Comment by eco32i** [comment]
I am having the same issue with .NEF files from D200 on beta14.  It was working on both 3.9 and 4.0

**Comment by ktgw0316** [comment]
Both D90 and D200 are working without the error on v4.1.0~rc1.
