### ISSUE TITLE
1:1 cropping makes non-square result

### ISSUE THREAD

**Issue by ktgw0316** [Aries85/LightZone#135]
When using 1:1 aspect ratio in cropping the resulting image is not a square. there is an error of 1 or 2 pixels. This happens only to images that are originally portrait.

This issue was reported at http://lightzoneproject.org/lorum/11-aspect-ratio-not-square

Related issue: #29

**Comment by juhavlintula** [comment]
Hi!

I just noticed, that this issue has been closed a year ago. Unfortunately this is not fixed. I tried with the latest version from the Github and the issue is still there. This might be the same as #204 

-Juha
