### ISSUE TITLE
Lightzone doesn't open RawTherapee saved Tiff (from Canon CR2 raw)

### ISSUE THREAD

**Issue by charliemb2** [Aries85/LightZone#142]
Lightzone doesn't open RawTherapee saved Tiff files that were opened in RawTherapee from a Canon 5Diii CR2 raw file and a Canon 5D CR2 raw file.   The Tiff is 16 bits uncompressed.

Lightzone opens other Tiff files from other cameras and also converted from RawTherapee.

The problemtic Tiff file opens okay in Photoshop; and, if resaved as a Tiff from within Photoshop CS3, without any pixel level modification, Lightzone will open that newly saved Tiff just fine.  

The file is not over 200MB.

The file contains no alpha channel.

I will test to see if the file can be opened in Photoline and Irfanview.

Should I upload the file somewhere?

I'm using the latest stable releases of both LZ and RawTherapee,  both downloaded this week.

(I searched both new and old issues,  and although there seems to have been some problems with 16-bit Tiffs, this particular problem with Canon CR2s appears to be unreported as of yet.  I'm surprised to be the first to report this given the popularity with Canon 5D and 5Diii.)

Charlie

Update 1:  Oddly, LightZone successfully reads 16 bit *compressed* Tiffs.  So the problem appears to be limited to uncompressed Tiffs saved by Rawtherapee and originating from Canon CR2 formats tried so far.

**Comment by charliemb2** [comment]
Update 2:  Irfanview successfully opens the troublesome Tiffs.

**Comment by ktgw0316** [comment]
I found the cause of this issue. There is an explanation in com.lightcrafts.image.types.TIFFImageType, line 315:

```java
        // Some camera vendors, in their infinite wisdom, decided, for some of
        // their cameras, to create raw files with a .TIF extension.  Since the
        // file isn't really a TIFF file, the ImageType returned by
        // ImageType.determineTypeByExtensionOf() is wrong.  If we were to try
        // to read one of these raw files as a TIFF, reading the full-sized
        // image doesn't work (you get the thumbnail instead).
        //
        // We therefore have to probe the image file to determine whether it's
        // really one of these raw image files.
        //
        for ( TrueImageTypeProvider p : m_rawImageProbes ) {
            final ImageType t = p.getTrueImageTypeOf( imageInfo );
            if ( t != null )
                return t;
        }
```

and these code correctly works for Canon EOS-1D and EOS-1Ds, which use ".tif" extension for their raw files. However, this causes false positive in converted tiffs from other models, when a raw converter used preserves a Canon metatag.

So I'll modify com.lightcrafts.image.types.CanonTIFFRawImageProbe#getTrueImageTypeOf(ImageInfo) to check the camera model to fix this issue.

**Comment by charliemb2** [comment]
Thanks
