### ISSUE TITLE
Default right panel width is too narrow

### ISSUE THREAD

**Issue by ktgw0316** [Aries85/LightZone#145]
"When launched, the right panel is too narrow. For example, the pink ball is hidden from a tool's Color Selection, and Tool Opacity slider is partially hidden."

Original report: http://lightzoneproject.org/comment/6092#comment-6092

**Comment by Photonoxx** [comment]
Is there something to do for this enhancement take effect ?

In both Linux and Windows, the right panel width of the editor is still too narrow, even after reset preferences (tested on windows).

**Comment by ktgw0316** [comment]
I misunderstood. This issue wasn't fixed by commit 108d27b.

**Comment by Photonoxx** [comment]
All I can say is with V4.1, both under Linux or Windows, the right panel is still too narrow.

Apparently, on Mac too if I read this thread : 
http://www.lightzoneproject.org/lorum/lz-41-toolbar-right-not-opening-fully-mac

Is the commit is hardcoded in the LZ executable or does't it affect a setting file somewhere which I can check ?

**Comment by ktgw0316** [comment]
The cause of this issue was hardcoded, so I had to modify and rebuild the code.
