### ISSUE TITLE
[patch] LightZone 4.1.2 RPM spec for CentOS 7

### ISSUE THREAD

**Issue by william8000** [Aries85/LightZone#156]
I made some small changes to the RPM spec to make a lightzone 4.1.2 RPM for CentOS 7.
I posted the spec on [dropbox](https://www.dropbox.com/s/nfcl62fdhw3ai8b/lightzone.spec?dl=0).
I also had to build a javahelp2 RPM for CentOS 7. I used a javahelp2 source RPM for Fedora 20.  Newer versions of javahelp2 require maven macros to build.
I can post the RPMs for a short time if anyone wants.
To make the lightzone RPM, I ran
```
git clone https://github.com/ktgw0316/LightZone.git
mv LightZone lightzone-4.1.2   
tar cjf lightzone-4.1.2.tar.bz2 lightzone-4.1.2/* lightzone-4.1.2/.travis*
mkdir $HOME/rpmbuild $HOME/rpmbuild/RPMS $HOME/rpmbuild/RPMS/x86_64 $HOME/rpmbuild/SOURCES $HOME/rpmbuild/SPECS
cp -p lightzone-4.1.2.tar.bz2 $HOME/rpmbuild/SOURCES/
cp -p lightzone-4.1.2/linux/lightzone.spec $HOME/rpmbuild/SPECS/ 
cd $HOME/rpmbuild/SPECS/
edit lightzone.spec
rpmbuild -ba lightzone.spec
```
Regards,
William Bader, Director of Research and Development at [SCS](http://www.newspapersystems.com)
williambader@hotmail.com

**Comment by ktgw0316** [comment]
Great, thanks! I merged your patch today: 8c9f27f

**Comment by william8000** [comment]
Thanks!
I should have added that on CentOS7, /etc/macros/macros.dist has
%centos_ver 7
%centos 7
%rhel 7
%dist .el7.centos
%el7 1
so probably testing for rhel should work for both RHEL and CentOS.
Regards,
William

**Comment by ktgw0316** [comment]
Both of javahelp2 and lightzone packages for CentOS 7 successfully build on OBS, so I close this issue.
