### ISSUE TITLE
javahelp is abandoned

### ISSUE THREAD

**Issue by Justinzobel** [Aries85/LightZone#158]
javahelp is now abandoned by sun and the links in it's build.xml don't work, specifically jdic binaries.

Is there any way to build without javahelp2? 

I've also posted on the forums here: http://lightzoneproject.org/lorum/javahelp-dependency

**Comment by ktgw0316** [comment]
Which distribution are you using?

**Comment by Justinzobel** [comment]
Solus, I'm trying to package it for the repository. https://solus-project.com/

**Comment by ktgw0316** [comment]
I have no experience on Solus, but I guess that you can build javahelp2 if you already have jdk and apache-ant, regarding Arch Linux PKGBUILD and Debian debian/rules scripts.

1. Download and extract the javahelp2 source.
2. Edit `javahelp_nbproject/build.xml` and delete `unpack-jdic-jar` from `-pre-init` target's `depends` attribute (line 48).
3. `rm jhMaster/JavaHelp/src/new/javax/help/plaf/basic/BasicNativeContentViewerUI.java`
4. `cd javahelp_nbproject && ant release`

Hope this helps.

**Comment by Justinzobel** [comment]
Seems to be trying to download more content from the internet that also doesn't exist.

+ ant release
Buildfile: /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/build.xml

build-jsearch-jars:

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-macrodef-javac:

-init-macrodef-junit:

-init-macrodef-nbjpda:

-init-macrodef-debug:

-init-macrodef-java:

-init-presetdef-jar:

init:

deps-jar:

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-macrodef-javac:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:javac

-init-macrodef-junit:

-init-macrodef-nbjpda:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:nbjpdastart

-init-macrodef-debug:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:debug

-init-macrodef-java:

-init-presetdef-jar:

init:

deps-jar:

download-tomcat-zip:
     [echo] Downloading Apache Tomcat for servlet-api.jar and jsp-api.jar
      [get] Getting: http://archive.apache.org/dist/tomcat/tomcat-5/v5.5.20/bin/apache-tomcat-5.5.20.zip
      [get] To: /tmp/apache-tomcat-5.5.20.zip

unpack-servlet-jar:
     [echo] Unpacking /tmp/apache-tomcat-5.5.20.zip
    [unzip] Expanding: /tmp/apache-tomcat-5.5.20.zip into /tmp
     [copy] Copying 1 file to /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/lib

unpack-jsp-jar:
     [echo] Copying /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/lib/jsp-api.jar
     [copy] Copying 1 file to /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/lib

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-macrodef-javac:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:javac

-init-macrodef-junit:

-init-macrodef-nbjpda:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:nbjpdastart

-init-macrodef-debug:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:debug

-init-macrodef-java:

-init-presetdef-jar:

init:

deps-jar:

-pre-pre-compile:
    [mkdir] Created dir: /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/build/classes

-pre-compile:

-do-compile:
    [javac] Compiling 137 source files to /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.4
    [javac] warning: [options] source value 1.4 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.4 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/jhMaster/JavaHelp/src/new/javax/help/plaf/basic/BasicNativeContentViewerUI.java:54: error: package org.jdesktop.jdic.browser does not exist
    [javac] import org.jdesktop.jdic.browser.WebBrowser;
    [javac]                                 ^
    [javac] /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/jhMaster/JavaHelp/src/new/javax/help/plaf/basic/BasicNativeContentViewerUI.java:70: error: cannot find symbol
    [javac]     private WebBrowser html;
    [javac]             ^
    [javac]   symbol:   class WebBrowser
    [javac]   location: class BasicNativeContentViewerUI
    [javac] /home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/jhMaster/JavaHelp/src/new/javax/help/plaf/basic/BasicNativeContentViewerUI.java:98: error: cannot find symbol
    [javac] 	html = new WebBrowser();
    [javac] 	           ^
    [javac]   symbol:   class WebBrowser
    [javac]   location: class BasicNativeContentViewerUI
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 3 errors
    [javac] 4 warnings

BUILD FAILED
/home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/build.xml:119: The following error occurred while executing this line:
/home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/JSearchIndexer_nbproject/nbproject/build-impl.xml:241: The following error occurred while executing this line:
/home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/JSearchClient_nbproject/nbproject/build-impl.xml:241: The following error occurred while executing this line:
/home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/nbproject/build-impl.xml:251: The following error occurred while executing this line:
/home/justin/YPKG/build/javahelp2/javahelp2-2.0.05/javahelp_nbproject/nbproject/build-impl.xml:134: Compile failed; see the compiler error output for details.

Total time: 12 seconds
Build failure: Command '['/bin/sh', '/tmp/eopkg-buildmN0VoX']' returned non-zero exit status 1

**Comment by Justinzobel** [comment]
Is it not possible to include the help files in the tarball instead of online? This would be better for users who work off-line as well.

**Comment by ktgw0316** [comment]
It seems that you skip the third step. The BasicNativeContentViewerUI.java should be removed.

The help files are not online but included in .jar file, so you don't need network connection to browse it.

**Comment by ktgw0316** [comment]
I tested the process in the [previous comment](#issuecomment-142194610) by myself on Solus in VirtualBox and it worked without any problem, so I close this issue now.
