### ISSUE TITLE
Adapted Lens reports incorrect aperture

### ISSUE THREAD

**Issue by jtpolk** [Aries85/LightZone#173]
The Metadata panel show Exposure as:

1/nn at f/1

This is when using a older mechanical lens with a dumb adapter, such as using a FD-M4/3 adapter with a Canon nFD 200mm F/4 Macro on an Olympus OM-D E-M5. I understand what is happening, where the metadata for F Number is 0, and it seems to either convert it 0 to 1, or it picks up the Max Aperture Value of 1 and puts that into Metadata Exposure information string. 

Outputting F/0 would not make any sense. Probably more work to change than it is worth, but it did surprise me when I saw a bunch of shots being shot at F/1.

later...

**Comment by ktgw0316** [comment]
If the aperture value is unknown or brighter than f/1.0, it will be shown as a question mark since LightZone v4.1.6.
