### ISSUE TITLE
New user on Mac OS X 10.11

### ISSUE THREAD

**Issue by geofones** [Aries85/LightZone#176]
Is there a version for 10.11 or will the 10.9 version work OK
Geoff

**Comment by ktgw0316** [comment]
AFAIK LightZone v4.1.5 has problems on OS X 10.11 El Capitan, though it works on 10.10 Yosemite. Dev-team is currently working on this.

**Comment by geofones** [comment]
Many thanks for your reply

**Comment by ktgw0316** [comment]
LightZone v4.1.7 works on El Capitan and Sierra. Feel free to reopen this issue if you have any problem on that version.
