### ISSUE TITLE
Decoding Sony DSC-RX1RM2 file fails

### ISSUE THREAD

**Issue by heckflosse** [Aries85/LightZone#179]
I tested with the example file from [here](https://github.com/Beep6581/RawTherapee/issues/3358#issuecomment-228205166).
https://github.com/Beep6581/RawTherapee/commit/cb05456746066b05fd9504ac3a3cb545a5b0debe
;-)
Edit: I tested using LightZone 4.1.6 (c0c5854)

**Comment by ktgw0316** [comment]
Great, thanks! :+1:

**Comment by heckflosse** [comment]
@ktgw0316 I saw you used the patch almost as is. But there may be an Issue with it:
Explanation: rt uses an own way to override the raw crops from dcraw. For that reason in rt dcraw patch we could safely eliminate the `width -= 32;` statement. If lz is not able to override the raw crops from dcraw, you may need to modify the patch. For reference: https://github.com/Beep6581/RawTherapee/issues/3361#issuecomment-229039243

Ingo

**Comment by ktgw0316** [comment]
Hmm..., I'll check it again when I have enough time.

**Comment by heckflosse** [comment]
;)
