### ISSUE TITLE
Lightzone in MacOs Sierra 10.12

### ISSUE THREAD

**Issue by jwathen1** [Aries85/LightZone#183]
WillLightzone be supported in MacOs Sierra 10.12?
The new OS will require gatekeeper or an identified developer.

Also it would be nice if it did not require an older version of java.

**Comment by ktgw0316** [comment]
LightZone v4.1.7 supports Sierra, and it includes Java 8 JRE so that you don't need to install old Java 6 from Apple.
You can run the app if you select "Open" in context menu (right click) on the application's icon.

If you have any trouble, feel free to reopen this issue.
