### ISSUE TITLE
Window Preference Location

### ISSUE THREAD

**Issue by Partha1b** [Aries85/LightZone#197]
I understand from the User Forum that LZ writes preferences into the Windows registry. This seems like a dangerous practise to me.

Is there a way to consolidate all settings into a more standard locations? For example, can the following be done?
Write everything to AppData\Roaming\LightZone:
Templates in AppData\Roaming\LightZone\Templates;
Logs in AppData\Roaming\LightZone\Logs
Preferences in AppData\Roaming\LightZone\Preferences

**Comment by ktgw0316** [comment]
Writing preferences into the Windows registry is a standard Java behavior, so I don't think it is dangerous at least manipulate the preferences via Java API.
