### ISSUE TITLE
Suggestion: Depreciate SHA1 Hashing for Install Files

### ISSUE THREAD

**Issue by jebeld17** [Aries85/LightZone#198]
_With the SHA-1 Hashing Algorithm officially depreciated by NIST back in 2011,_ it's time the SHA1.txt files used to verify [installation files for Mac and PC of LightZone](https://spideroak.com/browse/share/ktgw0316/lightzone/) be completely depreciated and replaced with a secure, advanced, compatible standard such as SHA256 or higher.
__

Sources:

[Stevens, Marc, Elie Bursztein, Pierre Karpman, Ange Albertini, and Yarik Markov. "The First Collision for Full SHA-1." _The first collision for full SHA-1_ (2017): 1-23. Web.](https://github.com/Aries85/LightZone/files/1050526/The.first.collision.for.full.SHA-1.pdf)

[SHAttered](https://shattered.io/)

**Comment by ktgw0316** [comment]
Done in 4.1.8. Thank you for the suggestion.
