### ISSUE TITLE
Lens info missing on Panasonic cameras

### ISSUE THREAD

**Issue by jonkerj** [Aries85/LightZone#200]
I recently started working with LZ and I think it is a great tool. It seems extracting lens info from Panasonic RW2 files is not implemented yet. I started digging in the source code and it is not implemented in the part that parses the maker notes: [PanasonicDirectory.java](https://github.com/Aries85/LightZone/blob/29efcb9f25fc49b608897597f84e00de2f45eddd/lightcrafts/src/com/lightcrafts/image/metadata/makernotes/PanasonicDirectory.java#L25).

**Comment by jonkerj** [comment]
I dug in the source code of [ExifTool](https://sno.phy.queensu.ca/~phil/exiftool/), which is able to extract the said info from my RW2 files. The LensID is taken from 0x0201 in the maker notes.

But here is where it becomes tricky for me: Panasonic and Olympus share "my" lens system (Micro Four Thirds), this is why ExifTool hides this code in `Olympus.pm`. I do not know whether to implement this in `PanasonicDirectory.java` or in `OlympusDirectory.java`, or in some common part included by both. Same goes for the `xxxTags.properties` containing the list of lenses.

Any thoughts on this?

**Comment by jonkerj** [comment]
Dug a little deeper. It seems Panasonic or Olympus are picked based on the make-tag being either `OLYMPUS` or `PANASONIC`. Based on this, I'd propose the following:

- implement the extraction of the lens id in both `OlympusDirectory.java` and `PanasonicDirectory.java`
- implement the lookup of the lens somehow in something common (`MicroFourThirdsTags.java`?)
- glue this somehow together.

**Comment by jonkerj** [comment]
Implementing it in a way that works for both Panasonic and Olympus would either involve a duplicated property bundle `0201>*`, or introducing a shared code path which consults a shared bundle before/after the vendor specific bundle is consulted. As my main interest is getting it to work on my Panasonic camera, I am opting for the former, and leaving Olympus untouched (as I cannot test it properly).

**Comment by jonkerj** [comment]
I think I have implemented the lens type extraction code in the right way, but I'm struck with something else. In de case of Panasonic RW2 files, the maker notes (`0x927C`) are not processed somehow. I've added tons of debugging to [ExifParser.java](https://github.com/Aries85/LightZone/blob/29efcb9f25fc49b608897597f84e00de2f45eddd/lightcrafts/src/com/lightcrafts/image/metadata/EXIFParser.java#L353) and [ExifMetadataReader](https://github.com/Aries85/LightZone/blob/29efcb9f25fc49b608897597f84e00de2f45eddd/lightcrafts/src/com/lightcrafts/image/metadata/EXIFMetadataReader.java#L105), but it never seems to encounter a "maker note", which seems conditional to construct a `PanasonicDirectory` (or any directory at all). This results in only `CoreDirectory` and `EXIFDirectory` to be constructed, and both do not set CORE_LENS to something non-null. Pfff, this is starting to get a bit beyond my comfort zone.

**Comment by jonkerj** [comment]
I tried to run the metadata extraction code against a camera produced JPG instead of RW2. It turns out this does not extract lens data (or any maker note data at all), but this seems caused by a different issue.

While parsing the JPG, `EXIFMetadataReader` encounters the maker model tag, and tries to determine which directory to use, by comparing the model/make in the metadata against the several directory classes. At that point of extraction, `getDirectories()` returns 0 items, so no model/make will be returned and no maker model directory will be constructed. 

My guess is that the 0 items are because of the directory carrying the model/make is the current one, which will be added later on.

**Comment by jedd** [comment]
I'm an Olympus m43 user .. with one Panasonic lens.  :)

 Does this same issue crop up with lens manufacturers that make the same
lens but with Canon, Nikon, and other mounts  - while reporting the same
lens id?

**Comment by jonkerj** [comment]
No, I think this is unrelated to the fact that Panasonic/Olympus share a lens system. I have found some issues, and they are not related to the fact that non-native lenses are used. Besides, I am using both Pana and Oly lenses on my Pana body and none of them show up in the UI.

I have found the following issues around this subject:

1. The lens type extraction is not implemented for Panasonic
2. The maker note probes do not work properly in my situation, maybe all situations. Workaround in previous comment.
3. There is an issue with ASCII values being all `null` in the maker notes after above fixes.

**Comment by jonkerj** [comment]
I've forked the repo and created a [branch](/jonkerj/Lightzone/tree/panasonic-lens-type) to work on this issue. LightZone correctly extracts lens info on JPG pictures now, RW2 is a total different story. I am afraid the info resides in the embedded JPG thumbnail.

**Comment by jonkerj** [comment]
After some further examination, it seems that my RW2 files carry a thumbnail, which contain the maker model and lens info. The part of LightZone which extracts this thumbnail only yields a buffer with pixels (`RenderedImage`), without any metadata.

**Comment by ktgw0316** [comment]
This issue was fixed in #201.
