### ISSUE TITLE
Editing DNG files

### ISSUE THREAD

**Issue by juhavlintula** [Aries85/LightZone#203]
My new Huawei mobile phone has an ability to shoot RAW and they are stored as DNG. When I edit the DNG image in LZ and create a _lzn file, most of the EXIF info is lost.

Here is an example. https://www.dropbox.com/sh/q4r3vx3prw2pl4b/AAABn0WNkaakNG9Xs4TTKTVHa?dl=0

-Juha

**Comment by MJacal** [comment]
Juha, a lot of work has been done on metadata handling recently, did you try to build LZ from the master branch? I'm in a hurry right now, but a 2 weeks old (Ubuntu) LZ build displays more exif info than the last "official" Win version for your DNG: focal lenght and ISO.

**Comment by juhavlintula** [comment]
Thanks for the tip Jacal. I managed to build LightZone on my virtual Ubuntu. I will test does that version have the same issues.
-Juha

**Comment by ktgw0316** [comment]
i confirm this issue, too. I'll look into it.

**Comment by ktgw0316** [comment]
@juhavlintula Would you check if e3d6914 fix this issue?

**Comment by juhavlintula** [comment]
I tested with the new version, and now the EXIF data is copied correctly to the lzn-file.
