### ISSUE TITLE
Crop/Rotate after deploying the tool stack

### ISSUE THREAD

**Issue by juhavlintula** [Aries85/LightZone#208]
The crop/rotate should be applied after the tool stack. Now applying clone tool at the edges can result in black areas after cropping because part of source is outside the crop. This has been also discussed in the [LZ forum](http://lightzoneproject.org/lorum/better-control-cropping-and-rotation#comment-7675).

**Comment by ktgw0316** [comment]
This issue was already fixed in testing branch, and I cherry-picked the fix into master branch.
