### ISSUE TITLE
LightZone 4.1.8 fails to run

### ISSUE THREAD

**Issue by daved163g** [Aries85/LightZone#209]
Sad. I was looking forward to an upgrade.  My system is Windows 7 64 bit, fully up to date.
On Win7x64 the new version comes up with a message "Corrupted jar" before even showing the splash screen. After clearing the error the program does not run.
I tried both the upgrade and the fresh install options. I left the previous user data in place and I cleared it.
I tried installing the x86 version and that gets as far as the main window then dies: it just disappears.
I tried replacing all the .jar files from the previous version (4.1.7). No go.
Version 4.1.7 x64 works fine and can be re-installed OK. I will revert to that version for now.
Version 4.1.7 x86 worked fine on my old 32 bit Windows 7.
I am not a programmer. Please don't try to program me. If you was evidence files please explain in simple words how to obtain it, bearing in mind I have no development tools.

**Comment by ktgw0316** [comment]
Would you try a new 64bit package, "LightZone-Installer-4.1.8-20171226-amd64.exe"?

**Comment by juhavlintula** [comment]
The updated version works for me (Win10/64).

-Juha

**Comment by daved163g** [comment]
The new upload works perfectly.
Well Done and Thank you!
