### ISSUE TITLE
LightZone 4.1.8 crashes on Ubuntu 16.04 and Windows

### ISSUE THREAD

**Issue by merlinemrys** [Aries85/LightZone#210]
I can choose edit and an image will open, but then everything freezes.  I cannot click on anything -- styles, tools, menus, etc.  And the kill process function in System Monitor does nothing -- I have to do a manual power off.

**Comment by juhavlintula** [comment]
I did a fresh install on 17.10 64-bit and I haven't had any issues.

**Comment by OkieChaz** [comment]
I have the same problem with a Windows 7, 64-bit computer after installing v 4.1.8.  
I installed v. 4.1.8 over v 4.1.7 - didn't work as described above, even after rebooting computer. 

Uninstalled v 4.1.8, installed 4.1.7 and everything worked fine.

Uninstalled v 4.1.7, installed v 4.1.8 again - it still locked up when going into edit. 

Going back to v 4.1.7.

**Comment by juhavlintula** [comment]
I have to revert my comment, I'm experiencing the same freeze in certain conditions:

- LZ never freezes on a RAW
- LZ never freezes on JPG, when I selected a Style from the top menu
- LZ freezes on JPG, when I moved my mouse over the Style pane (no need to select a style)
- LZ freezes on JPG even if I had first selected a tool (e.g. Zones) or a style from the menu and moved my mouse over the Style pane

The same thing happens both on my fresh Ubuntu 17.10 and Win10/64

-Juha

**Comment by juhavlintula** [comment]
When LZ freezes, it consumes 100% of a single core.

**Comment by ktgw0316** [comment]
I think that commit 7567c12 fixed this issue.

**Comment by kross-uk** [comment]
ktgw0316 you've mentioned that commit 7567c12 fixed this issue, however, sadly I don't know what to do once I open that link, any chance that could be clarified please?
Many thanks.

**Comment by juhavlintula** [comment]
Hi kross-uk,

Are you on Win or Linux? If you are on Linux, then
    $ git clone https://github.com/Aries85/LightZone.git
and then follow the instructions in the linux page here in github (̧`https://github.com/Aries85/LightZone/blob/master/linux/BUILD-Linux.mḑ).
If you are on Windows, there is already an updated download package.

**Comment by juhavlintula** [comment]
After quick tests works now for me both in Win64 and Linux.

**Comment by OkieChaz** [comment]
The updated package seems to solve the problem.

Hooray!

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
