### ISSUE TITLE
4.1.8 freezes

### ISSUE THREAD

**Issue by yurivict** [Aries85/LightZone#213]
It prints these messages when I click on the photo:
```
Opening /usr/home/yuri/1304772.jpg
EventThread blocked for 2.005 seconds
EventThread blocked for 4.006 seconds
EventThread blocked for 6.007 seconds
EventThread blocked for 8.014 seconds
...
```

Found while trying to update the FreeBSD port.
I think, OpenMP is used now that wasn't used before. Maybe this is the problem? Any way to disable it?

LightZone-4.1.8

**Comment by pullmoll** [comment]
I'm the maintainer of the Void Linux package template for lightzone and can confirm that `LightZone-4.1.8` freezes after entering the edit mode. The selected image is displayed and then no more interaction is possible with lightzone's UI.

The Void Linux package `lightzone-4.1.8` is running under the `openjdk-jre-8u172b00` and `libgomp` is part of the `gcc-7.2.0` compiler in Void.

I also see the blocked messages:
```
Opening /home/jbu/Bilder/test.jpg
EventThread blocked for 2,000 seconds
EventThread blocked for 4,001 seconds
EventThread blocked for 6,001 seconds
EventThread blocked for 8,001 seconds
EventThread blocked for 10,002 seconds
EventThread blocked for 12,002 seconds
```

According to `ps` the process' command line is:
```
java -classpath .:/usr/share/java/lightzone/*:/usr/share/java/javahelp/jh.jar -XX:+UseG1GC -XX:MinHeapFreeRatio=30 -XX:MaxHeapFreeRatio=30 -Xmx19783680k -Djava.library.path=/usr/lib64/lightzone -Dfile.encoding=UTF8 com.lightcrafts.platform.linux.LinuxLauncher
```

Anything I can do to further identify the problem?

**Comment by ktgw0316** [comment]
I think that cause of this issue is same as #210.  I don't think that the OpenMP is relevant.

**Comment by pullmoll** [comment]
The code of commit https://github.com/Aries85/LightZone/commit/7567c1262a788524ae023c54bd0aae42a93d0fc8 is in 4.1.8 if I look at the source so no, it doesn't fix the problem.

**Comment by ktgw0316** [comment]
@pullmoll Thanks for the info. I'll setup Void Linux and/or FreeBSD on VIrtualBox and look into this issue.

**Comment by ktgw0316** [comment]
@pullmoll Could you update checksum in
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/lightzone/template
to c92666ebcb4d066a5acbe3c41b6c4d74f78f9ac68998e3ac8ac3e13bb316905e and try again?

**Comment by pullmoll** [comment]
@ktgw0316 I can confirm this build works. Thank you very much!
I'll update the Void Linux package now.

**Comment by ktgw0316** [comment]
@pullmoll Thanks, I'll close this issue.
