### ISSUE TITLE
An error opening/processing Ricoh GXR A12 *DNG files due possibly to regression (in LZ ver 4.1.8)

### ISSUE THREAD

**Issue by bcelasun** [Aries85/LightZone#217]
I fail to edit my files which I could do without problem until to date BOTH under Linux (host, 64bit) and Windows 7 (guest, 64 bit). All these files are in (previously working) *.dng format. The jpegs that were linked to them are also uneditable. 
The files can be  processed normally using other software (Darktable, Rawtherapee etc.).
LZ 4.1.8 seems to work without problem on my *.pef, *.tiff and *.jpg files.
The situation is replicated and confirmed by another user (Jacal) on his machines (Linux and Windows).
See: 
http://lightzoneproject.org/lorum/error-reading-file-unknown-maker-notes-header#comment-9224
Sample files are below:
https://filebin.net/5472aijf2c76tyfs

Thanks,

**Comment by ktgw0316** [comment]
This bug seems to be happen when the format is DNG and the camera name starts with "Ricoh".

**Comment by bcelasun** [comment]
I confirm that the bug has been removed. 
Many thanks!

**Comment by jhoenstine** [comment]
I am having the same problem with LZ 4.1.8 - tried to build from source but failed. How do you impalement the change. Thanks

**Comment by bcelasun** [comment]
As far as I remember, I had installed the fixed version.
Although the version number is still the same, now I am on Version 4.1.8 (fd9743b) and it runs nicely.

**Comment by bcelasun** [comment]
Oh wait!
MyLightZone also started misbehaving! It just crashes while opening a -previously fine- file. 
I have also noticed a strange error message but I cannot replicate it. LZ just crashes!
I guess there is some interaction with my updated system files. Strange, since LZ mostly runs on its own JRE.

**Comment by jhoenstine** [comment]
Thanks - I have purged LZ and reinstalled from the PPA  but still cannot edit Ricoh files. Will probably  just go to RawTherapee for all my raw processing because it also does the Pixel Shift which was the only thing I was using it for.

**Comment by MJacal** [comment]
The current PPA version is older than this fix.
