### ISSUE TITLE
Olympus OM-D E-M1 MkII geotagged files fail

### ISSUE THREAD

**Issue by juhavlintula** [Aries85/LightZone#219]
I took some pictures with my E-M1 MkII and used the Olympus Image Share app to geotag the pictures. When I try to edit my images in Lightzone, the save operation fails with message
```
Couldn't save to .../LZExport3749667101062053873.tmp
JPEG export failed
```
When I started LZ from command line in Linux I got the attached error messages on the console. I haven't had any issues with RAW files without the geotags. I have uploaded the image P1200093.ORF in Dropbox (https://www.dropbox.com/sh/q4r3vx3prw2pl4b/AAABn0WNkaakNG9Xs4TTKTVHa?dl=0). (In the error log there are similar messages on image P1200116.ORF at the beginning, but it was P1200093 I tried to edit.)

[Olympus_error.txt](https://github.com/Aries85/LightZone/files/1649232/Olympus_error.txt)

**Comment by MJacal** [comment]
Fix 219 seems to have solved the problem.

**Comment by juhavlintula** [comment]
Confirmed.
