### ISSUE TITLE
UTF-8 Characters not supported

### ISSUE THREAD

**Issue by juhavlintula** [Aries85/LightZone#225]
Accented place names that are stored in as UTF-8 (like Österreich) get corrupted.

**Comment by ktgw0316** [comment]
Could you provide links to sample pictures?

**Comment by juhavlintula** [comment]
HI!

I have copied an example in Dropbox (https://www.dropbox.com/sh/q4r3vx3prw2pl4b/AAABn0WNkaakNG9Xs4TTKTVHa?dl=0); IMG_7025.jpg and IMG_7025_lzn-2.jpg. There are umlaut characters both in place and in keywords.

**Comment by ktgw0316** [comment]
I've just fixed this issue, so LZ won't corrupt UTF-8 letters anymore, but you need to fix the already corrupted letters by yourself using exiftool, etc. Sorry about that.
