### ISSUE TITLE
Weird color issue and ICC color profile warning with PS import

### ISSUE THREAD

**Issue by Aaron801** [Aries85/LightZone#228]
I've used lightZone for several years with no issue (great program!) but recently, I've been having some very odd problems. When I save a file that I've been working on (that I've converted to B&W, incidentally) I get something with very odd colors if I save it as a Grey Tone file and if I save it as web save colors it's solid black. With the Grey Tone one I get a warning that Photoshop doesn't recognize the ICC profile when I try an import into that program and if I ignore this and open it anyway in PS, the file looks the same as the preview, with odd colors. This happens whether or not I save as TIFF or JPEG. 

I tried all of the obvious stuff, like restarting the program, restarting my computer (a Mac) and even downloading and reinstalling the newest version of the software (which is what I was using before). Everything seems to work fine inside the program, but the saving part doesn't seem to work at all. Also, I've noticed that there are less options when I go to save. I see "web safe colors" but no longer see an option to save with the sRGB color. There may be other options that also aren't coming up in that particular window. 

Any advice is very much appreciated as I have lots of files that I'd like to be processing in LightZone. 

Enclosed here is the file that I get when I save my B&W image as a Grey Tone JPG.
![sawz](https://user-images.githubusercontent.com/40524938/41812090-2dafb2fc-76d1-11e8-9e53-3c4c67fc7c6f.jpg)

**Comment by MJacal** [comment]
Opening this file, the Gimp says "ICC profile validation failed: Color profile is not for RGB color space". ExifTool says, it is an Apple Gray Tone profile.
Can you provide the original file?

**Comment by Aaron801** [comment]
Enclosed is the lzn file. I'm not sure what you're saying about the information that you found on Gimp and from the ExifTool. The previous file was just what LightZone generated when I took a B&W image that I was working on and attempted to generate a greyscale (or "Grey Tone" as it's called in the covert menu). I've actually tried to do the very same thing with an older RAW file that I had successfully generated a JPG with previously and got the same result... so I don't think that the issue is with the file. As I said, I remember that there were other options in that particular menu before. I no longer see the option of sRGB... and was there every a CMYK option as well?

Is there perhaps a way to clear the cache/reset the program (while still hopefully being able to keep my presets, though I'm OK with trashing them if I really need to)? 



![p6220097_lzn](https://user-images.githubusercontent.com/40524938/41814264-68793d74-76fc-11e8-8101-ef98ad8dc594.jpg)

**Comment by Aaron801** [comment]
OK... I figured out how to clear out the app cache and did that. I also went into the preferences and hit the reset LightZone settings, restarted the program and have the exact same issues; when I save as Grey Tone, I get that weirdly colored file and the save color option menu is still missing the sRBG option that it used to have. Is there anything else that I might try that would be likely to restore the program to it's correct operation?

**Comment by Aaron801** [comment]
Really, no more advice? 

LightZone had been my favorite software to use for editing photos from raw files, particularly when it comes to B&W conversions. I've edited thousands of photos in the last 5 years or so with the program, since I downloaded it. It's unfortunately no longer of any use at all to me since I'm unable to export either JPG or TIFF files with it (so I can't really do anything with it). This is really going to be particularly inconvenient for me when it comes time to re-edit numerous photos that I've done in LightZone as I often go back to old photos to improve on them or to regenerate in a different size or format.  

Posting in this forum here was my final effort to fix this thing as I read up on common issues on the LightZone site and tried surfing around the web for any answers... I wonder at least if you know of any other software that can read my old .lzn files?

**Comment by jedd** [comment]
Hi Aaron,

I suspect there's not a lot of Mac users here, so there's not that many people who can offer platform specific advice.  That other Mac users aren't seeing (or at least aren't reporting) the same thing may reflect an edge case / bug you've discovered, or that it's peculiar to your machine.

It's not very clear what other changes happened before or around the time that you noticed this bug?

You mentioned you re-installed the latest version, but didn't mention if you'd tried installing an earlier release, or rolling back other software changes you made just prior to noticing the problem.

If you've got access to another Mac, it'd be great if you could try the same source (image) file and repeat the operations.  Actually, if you've access to a different OS as well that would also be useful to repeat your workflow with the same version of LightZone and the same input files.  If you don't have convenient access to a different OS, is it feasible to crank up a virtual image of a GNU/Linux distro for purposes of testing?

You mentioned a bunch of options have disappeared from some menus - this sounds alarming, especially if it didn't involve a version change of LightZone.  Perhaps some screen shots of the dialogs / menus that you think have changed, with some notes on what they looked like previously.

I'm sure this problem is resolvable, it'll just take a bit of troubleshooting.

**Comment by MJacal** [comment]
(Thanks, jedd, this is much better than what I wanted to write down, having only Windows and some Ubuntu experiences. The lzn file from the third post contans data that look like normal editing information.)

**Comment by Aaron801** [comment]
I'm at a loss really... All of these problems pretty much popped up out of nowhere. I didn't upgrade my OS or make any other changes to my system before it happened. I don't actually have another Mac that I can test the software out on, but even if I did I'm not quite sure what this would prove. I'm not sure that I'm savvy enough to get that Linux thing to work as I haven't done anything like that in the past. I have on many occasions fixed various software issue by getting information via the web (just as I'm attempting to do now) but this issue that I'm having with LightZone seems to be far more fatal and as of now, impossible to get the correct info to do much about (that is, without getting into some deeper level stuff that I lack the knowhow to deal with). 

I have to wonder, if the lzn file is indeed correct, if the issue isn't solely with the conversion end of the software and not in the LightZone files...? This knowledge actually isn't going to be of much use to me, but might help the experts to hone in on what the real culprit is.

Enclosed are a couple of screen shots of the what the export panel looks like on my end. Hopefully this will provide some clues. The one image shows the color profile menu and how the sRGB option is missing. There may actually be other missing options as well but I don't clearly remember what all of the options were back when the program was working correctly. 

I may try finding an older version of the program and downloading that to try... I can proably live without some of the new features and fixes as long as everything is working correctly on a basic level.

Thanks for your help in all of this

![screen shot 2018-06-26 at 3 55 26 pm](https://user-images.githubusercontent.com/40524938/41943718-594aa93c-7959-11e8-97eb-29df96b2b245.png)
![screen shot 2018-06-26 at 3 54 51 pm](https://user-images.githubusercontent.com/40524938/41943719-59775478-7959-11e8-9512-b8af77d7b994.png)

**Comment by ktgw0316** [comment]
@Aaron801  Could you show me lists of files under these three folders?
- /System/Library/ColorSync/Profiles/
- /Library/ColorSync/Profiles/
- (Your home directory)/Library/ColorSync/Profiles/

LZ ignores the first one. I guess that is why some profiles are missing, and that is a bug in LZ:  https://github.com/Aries85/LightZone/commit/f7a08401b#diff-f013c55

As a side note, I found a similar bug report for Inkscape:  https://bugs.launchpad.net/inkscape/+bug/494932

However, the "Photoshop doesn't recognize the ICC profile" message about the Gray Tone is another problem. I'll look into it.

**Comment by Aaron801** [comment]
Ok.... First of all, thanks so much with your help with this thing. I really appreciate it. LZ is really important to what I do as I do lots of photography and though I have other software, most of it is processed with LZ. I have a show of my work coming up which if I wasn't able to generate higher rez copies of my work from my old lzn files, it would mean an awful lot of work in attempting to get the same look with other software. 

After trying so much other stuff, I restored my LZ to an older version that I was using, v 4.1.3 and finally I got that to work. I think that this version might be one that doesn't have the correct raw file for my camera, an Olympus EM10, however I was able to get things to look pretty close to the way I think they should by pushing the luminance up on all files. I do like the idea of working with something that's specifically designed for my camera so perhaps when there's another LZ update, I'll temp fate and download that one... For the time being though it seems that I have everything working as I've experimented outputting both B&W and color jpgs and tiff files with no glitches so far...

Enclosed is a screenshot that I just took of the color profile menu in the output panel and as you can see, rather than there being 8 or 10 options there's probably close to 50. I feel that the fact that there were so few options for color profiles before might be some kind of clue to the issues with output (but might not explain why the 4.1.7 version that I tried crashed as soon as I oped up any file to edit). Oddly enough the 4.1.3 version that I've just got to work properly in it's long list of color profiles doesn't even have options for anything like "Grey Tone" or "Web Safe Colors," which actually did sound odd to me when I realized that they were some of the very few options available on the 4.1.8 version which I was having so much trouble with...

![screen shot 2018-06-27 at 10 40 09 am](https://user-images.githubusercontent.com/40524938/41990271-c90cdb58-79f6-11e8-8b60-7cd86aa465af.png)

**Comment by ktgw0316** [comment]
I've just modified source code to add the ```/System/Library/ColorSync/Profiles/``` in color profile search path, so this issue will be fixed in v4.1.9.

As a temporary workaround for v4.1.8, you can copy icc profiles from the ```/System/Library/ColorSync/Profiles/``` to ```(Your home directory)/Library/ColorSync/Profiles/```. Note that this workaround won't work for older versions than v4.1.8.

**Comment by ktgw0316** [comment]
As for the 'Gray Tone' profile, its color space is Lab, but Photoshop and Gimp cannot render it as is, and render it as if it is an RGB image. I mean, when the image is rendered, ```L``` channel is used as ```R``` channel, ```a``` as ```G```, and ```b``` as ```B```. This is why the image was rendered in odd color instead of grayscale.

If you want to render correctly in PS/Gimp, decompose the RGB components into three different layers, then combine them as LAB. I tested this on Gimp (Colors -> Components -> Decompose/Compose), but I guess PS has the same feature.

If you just want to convert some images into grayscale, I recommend you not to use the 'Gray Tone' profile. Use 'Black and White' tool or 'Hue/Saturation' tool with Saturation = 0, then save with sRGB profile.

**Comment by Aaron801** [comment]
Thanks for all of your work in figuring this out. Right now I'm using an older version, which seems to work OK (thus far). I don't know if I mentioned but I was using the current version for quite a while before I had all of these issues (and options seemed to disappear from menus). 

Using this old version, though it lacks direct compatibility for my camera still seems preferable to using the current version and having to deal with the conversion thing with Photoshop to get a B&W image... not to mention that the only option for color is "Web Safe Color" and that resulted in a totally black image. I understand Photoshop very well and I think that I could do that LAB conversion thing that you mention (though I've never bothered to work in LAB color space), but it seems like a lot to go through every time I want to generate a JPG. 

I'll be eagerly awaiting the v4.1.9 version... Overall, I really like the program, particularly for B&W as the conversion controls and the ones for setting tones and contrasts are very well thought out.

Thanks again for your efforts.

**Comment by ktgw0316** [comment]
I think this issue is fixed in 4.1.9.
