### ISSUE TITLE
Install failed on CentOS 7

### ISSUE THREAD

**Issue by humantex** [Aries85/LightZone#230]
I followed the linked page's instructions for the install commands for root...
```
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:ktgw0316:LightZone/CentOS_7/home:ktgw0316:LightZone.repo
yum install lightzone
```
The repo was installed and yum responded correctly to get the packages, but declared that there's a dependency issue with **javahelp2** that can't be resolved, and yum wouldn't complete the install.

I also tried the suggested **--skip-broken** parameter, but only the dependency message went away, and it still wouldn't install.

CentOS version: 7.5.1804 (core)
Kernel: Linux 3.10.0-862.6.3.el7.x86_64 (x86_64)

**Comment by ktgw0316** [comment]
I've just make the ```javahelp2``` package available from the repo.
