### ISSUE TITLE
Converted TIFFs still lack some EXIF information

### ISSUE THREAD

**Issue by juhavlintula** [Aries85/LightZone#231]
The issue #223 still not fully corrected on the latest commit #8002558. See image P6030538 in [Dropbox ](https://www.dropbox.com/sh/q4r3vx3prw2pl4b/AAABn0WNkaakNG9Xs4TTKTVHa?dl=0) (P6030538_417.tif is converted with LZ 4.1.7 and it's correct). The exposure information is missing and the used focal length, also the camera body + lens information is different between the LZN file and the TIFF file.

**Comment by ktgw0316** [comment]
I think commit c638c5d and 2dfc39e fixed this issue.

**Comment by juhavlintula** [comment]
I tested the latest commits and there is still something. When I uploaded the new converted TIFF into my DAM tool it didn't read vendor and camera model. When I listed the tags with exiftool, but they were preceded by Warning "Bad IPTC data tag (marker 0x0)". The comparison between 4.1.7 and 4.1.8 (with latest patches) is in the attached Excel file.

[LZ_diffs.xlsx](https://github.com/Aries85/LightZone/files/2242739/LZ_diffs.xlsx)

I have also uploaded the example images in Dropbox (P6050696).

**Comment by juhavlintula** [comment]
I have also reported the issue to the DAM vendor as the camera vendor and model tags exist in the generated TIFF.

**Comment by ktgw0316** [comment]
I couldn't reproduce this issue. I uploaded the tiff in Dropbox ([P6050696_c638c5d.tif](https://www.dropbox.com/s/w5m2g8hb45efb8r/P6050696_c638c5d.tif?dl=0)), which was converted using 4.1.8 with the latest patches.

**Comment by juhavlintula** [comment]
I tested with your image and all the tags were imported correctly into my DAM system. Also there was no "Bad IPTC data tag (marker 0x0)" warning. When I generated the TIFF, I still got the same error and not all tags are imported; I have tested with compressed and uncompressed images and full-size and limited to 2560×2560. What could be the different in my environment?

I'm running 64bit Ubuntu 18.04 and Java openjdk 10.0.1 2018-04-17. There was an issue with jni.mk (line 198) as javah has been dropped. I installed Java-8 and redefined JAVA_HOME. What else I could check?

**Comment by ktgw0316** [comment]
OK, I could reproduce it. The IPTC data was written when I exported in Edit mode, but not in Browser mode.

The IPTC data length was treated differently in LZ's Java code and libtiff, and libtiff added junk data on tail of the IPTC data. I've just fixed this issue in 53e6ca5.

**Comment by juhavlintula** [comment]
Verified and exiftool reported no errors.
