### ISSUE TITLE
LightZone 4.1.8 (3cb2bc3) crashes on fresh Ubuntu 18.10

### ISSUE THREAD

**Issue by juhavlintula** [Aries85/LightZone#234]
I made a fresh install on a fresh Ubuntu 18.10 and LightZone crashes when I select a folder with images. I get an error message
``` 
     ...
     [java] Scanning Saved Documents
     [java] Opening...
     [java] Light Crafts JAI Library - 02/05/07
     [java] /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java: symbol lookup error: /home/lintujuh/LightZone/lightcrafts/products/libLCLCMS.so: undefined symbol: cmsOpenProfileFromMem
```
I tried both with default Java-11 and also with Java-8 with same results. There was an old issue #124, could this be related?

**Comment by juhavlintula** [comment]
On Ubuntu 18.04 (where I had an older installation) the version works fine.

**Comment by juhavlintula** [comment]
Yes, I checked it before I created the ticket. It is at version 2.9-3.

**Comment by juhavlintula** [comment]
Lightzone only fails during the test run ("ant build run"). When I build and install the package, Lightzone doesn't crash. (I don't know if the color management is working though).

**Comment by ktgw0316** [comment]
I see. Could you try the latest 6126a0f?

**Comment by juhavlintula** [comment]
It starts to scan the folder, but fails during the process.
```
     ...
     [java] Scanning Saved Documents
     [java] Opening...
     [java] Light Crafts JAI Library - 02/05/07
     [java] /usr/lib/jvm/java-11-openjdk-amd64/bin/java: symbol lookup error: /home/lintujuh/LightZone/lightcrafts/products/libLCLCMS.so: undefined symbol: cmsOpenProfileFromMem

BUILD FAILED
/home/lintujuh/LightZone/linux/build.xml:106: Java returned: 127
```

**Comment by ktgw0316** [comment]
Would you show me output from following commands?
  - ```ldd /home/lintujuh/LightZone/lightcrafts/products/libLCLCMS.so```
  - ```ldd /usr/lib/lightzone/libLCLCMS.so```
  - ```pkg-config --libs-only-l lcms2```

Please make sure to do ```ant clean && ant``` before these commands.

**Comment by juhavlintula** [comment]
I executed commands `ant -f linux/build.xml clean && ant -f linux/build.xml`

The output is
```
lintujuh@lintujuh-VM:~/LightZone$ ldd /home/lintujuh/LightZone/lightcrafts/products/libLCLCMS.so
	linux-vdso.so.1 (0x00007ffdbb5b0000)
	liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f1eeaba0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1eea9b6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1eea829000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1eea808000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1eeac16000)
lintujuh@lintujuh-VM:~/LightZone$ ldd /usr/lib/lightzone/libLCLCMS.so
	linux-vdso.so.1 (0x00007ffeceba1000)
	liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007fc910b65000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc91097b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc9107ee000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc9107cd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc910bdb000)
lintujuh@lintujuh-VM:~/LightZone$ pkg-config --libs-only-l lcms2
-llcms2
```

Now `ant -f linux/build.xml run` works. My mistake, I didn't do `clean`, when I tried the updated version.

**Comment by ktgw0316** [comment]
Thanks for the info. It seems to be fixed now. :)
