### ISSUE TITLE
Unable to Run 4.1.9 on OSX

### ISSUE THREAD

**Issue by dakanji** [Aries85/LightZone#237]
Get a series of errors trying to run LZ 4.1.9 on OS X.

My machine specs are:
![mod elcapitan screenshot](https://user-images.githubusercontent.com/1128876/50512472-23ea1080-0aa3-11e9-8a67-ec848410f007.jpg)

Once I click on LZ, I just get a series of errors and it become unresponsive.

Error Message 1:
![lz-error-01](https://user-images.githubusercontent.com/1128876/50512444-f604cc00-0aa2-11e9-8914-e1fe54fd14e1.png)

Error Message 2:
![lz-error-02](https://user-images.githubusercontent.com/1128876/50512506-5ac02680-0aa3-11e9-9837-985bc66be2ba.png)

Final Message:
![lz-error-03](https://user-images.githubusercontent.com/1128876/50512517-64e22500-0aa3-11e9-84d3-7c35fc3a9e0e.png)

**Comment by ktgw0316** [comment]
Please try this new package:
https://github.com/ktgw0316/LightZone/releases/download/4.1.9/LightZone-4.1.9-20181229.dmg

**Comment by dakanji** [comment]
Thanks. It works.
