### ISSUE TITLE
Windows XP SP3 - libwinpthread-1.dll not found

### ISSUE THREAD

**Issue by cgpurbaugh** [Aries85/LightZone#239]
Error message:

"This application has failed to start because libwinpthread-1.dll was not found. Re-installing the application may fix this problem."

Re-install did nothing.

**Comment by conh7** [comment]
I had the same problem when I downloaded the 32 bit. Try the 64 one.

**Comment by cgpurbaugh** [comment]
@conh7 It's a 32 bit machine.

**Comment by ktgw0316** [comment]
I'll fix this issue in next release if I can.

As a temporally fix, download the 32-bit dll from following link and put it in the same folder as LightZone.exe.
https://www.dropbox.com/s/65l87hvlovn2rln/libwinpthread-1.dll

**Comment by cgpurbaugh** [comment]
@ktgw0316 Thanks for the fix!
