### ISSUE TITLE
Windows XP SP3 - Couldn't link with native library: "LCTIFF

### ISSUE THREAD

**Issue by chuahtc** [Aries85/LightZone#240]
Error message:

Couldn't link with native library: "LCTIFF

C:\Program Files\LightZone\LCTIFF.dll: Can't find dependent libraries

Needless to say, I can't preview nor edit TIFF files.

**Comment by NeilLomax** [comment]
Hi,
Anyone found an answer to this problem yet? I originally had the missing libwinpthread-1.dll which I fixed using the suggestion posted here. Now I get the above error. After clicking OK to the error message, LightZone then scans MyPictures, opens the application window and then closes it instantly. I then get a "failed to open" message if I try to re-open LightZone. I have tried resetting and not resetting the app but neither solve the problem I have also tried re-installing as well. Any help would be appreciated.

I am trying to run LightZone-Installer-4.1.9-20190109-32bit on a Windows XP Pro SP3 32-bit laptop with 2Gb of RAM.

**Comment by ktgw0316** [comment]
I think this issue is finally fixed by 6830152. Please try v4.2.0.

**Comment by chuahtc** [comment]
Ok, thanks.

But I don't think v4.2.0 can be installed under WinXP. I got the following error message when I tried:

"Application popup: LightZone_Installer_4.2.0_20200306_windows-x32.exe - Entry Point Not Found : The procedure entry point InitOnceExecuteOnce could not be located in the dynamic link library KERNEL32.dll. "

**Comment by ktgw0316** [comment]
Sorry, but Install4j, which we use to create the installers, is not support Windows XP now. I guess you can install on another Windows 10/8/7 machine then copy its `C:\Program Files (x86)\LightZone\` folder to the XP machine, although I don't recommend it.

**Comment by chuahtc** [comment]
Your recommended workaround doesn't work. Thanks for the suggestion anyway.
