### ISSUE TITLE
Couldn't link with native library : "LCLENSFUN

### ISSUE THREAD

**Issue by MacTerrassa** [Aries85/LightZone#248]
Hi: On two different machines (one with Mac OS X 10.11 and other with MacOS 10.15) An alert box appears when I start the program version 4.2.0, and even though it finally starts up completely, I still haven't checked if all its functions work correctly.
The content of the alert is:
Couldn't link with native library :"LCLENSFUN
/Applications/LightZone.app/Contents/MacOS/libLCLENSFUN.jnilib: dlopen (Applications/LightZone.app/Contents/MacOS/libLCLENSFUN.jnilib, 1): 
Library not loaded:@executable_path/libpcre.1.dylib. Reason: Image not found.

 I go back to previous version, 4.1.9 that I had not installed, and it starts fine without any alert.

Regards
PS: I do not speak English, message translated mechanically, I apologize if I have not expressed myself correctly.

Jose Luis

**Comment by ktgw0316** [comment]
Note for myself: 

- `/Applications/LightZone.app/Contents/MacOS/libglib-2.0.0.dylib` requires the missing `libpcre.1.dylib`
-  `macosx/postprocess.sh` should be fixed, in the same manner as commit 6830152

P.S. @MacTerrassa No problem, I'm not native speaker of English, either.

Masahiro
