### ISSUE TITLE
Fuji X100f - Java heap space

### ISSUE THREAD

**Issue by rg0001** [Aries85/LightZone#249]
In versions 4.2.0 and 4.2.1 of Lightzone, when you try to edit a *.raf file taken by the Fuji x100f camera, you receive the message "**_Insufficient memory to open this files_**" "**_Java heap space_**".

**Comment by MJacal** [comment]
I can confirm this on Windows 10, LZ 4.2.1.

No such problem on an Ubuntu Studio 20.04 virtual machine. LZ, built from master, opens the sample files (from raw.pixls.us), compressed and uncompressed, normally.
