### ISSUE TITLE
Lightzone version 4.2.2 for Windows 10 Doesn't Open. 

### ISSUE THREAD

**Issue by sfink16** [Aries85/LightZone#254]
Have to go back to version 4.2.1 to work. Apparently some missing files.

**Comment by ktgw0316** [comment]
You can anytime download the previous version from https://github.com/ktgw0316/LightZone/releases/tag/4.2.1
but I want to figure out which files are missing. Could you check Lightzone.exe using "dependencies" (https://github.com/lucasg/Dependencies ) ?

**Comment by sfink16** [comment]
Thanks, I'm already using 4.2.1 on my Windows 10 desktop.  4.2.2 works on my Ubuntu 20.04.  Please refer to Grant's post [HERE] for further detail.  I'm heading out of town for a few days and won't be able to test until I return.  

Steve Fink

**Comment by andrewk8** [comment]
> but I want to figure out which files are missing. Could you check Lightzone.exe using "dependencies" (https://github.com/lucasg/Dependencies ) ?

I ran DelendenciesGui on LightZone.exe 4.2.1 Windows x64.  I don't see a way to export the output.  See screen shot.

The CLI version won't produce output without specifying an option.  Which CLI option(s) will give you the output you want?

I scanned the Dependencies GUI and didn't see reference to any of the [17 .dll files referenced by Grant (December 19)](http://lightzoneproject.org/lorum/lightzone-422-windows-64-bit-crashes).

![2021-01-03 10_59_29-Dependencies (x64)](https://user-images.githubusercontent.com/16465258/103483687-fed9b800-4db6-11eb-9660-8cf39402e25b.png)

**Comment by ktgw0316** [comment]
Thank you for the info. I overlooked the Grant's post. Anyway, I still have a login problem so I can't post on the forum.

I found the cause of this issue last night. I'm going to release fixed packages as soon as possible, so please wait for a while.

**Comment by ktgw0316** [comment]
I've just uploaded a new installer for 64bit Windows on the release page. 32bit version is still under construction.

**Comment by andrewk8** [comment]
> I've just uploaded a new installer for 64bit Windows on the release page. 32bit version is still under construction.

Windows x64 4.2.2 is working now.  Thanks!
