### ISSUE TITLE
Edit mode doesn't render whole image (Win64)

### ISSUE THREAD

**Issue by RussellAult** [Aries85/LightZone#255]
This is very similar to what was described in #251 (screenshot would be identical). I recently upgraded to 4.2.2 from 4.1.9, which didn't have this problem.

When I open an image in Edit mode, only some parts of the image are displayed. If I make enough adjustments to tools the whole image will eventually load, but the adjustments won't appear to have been applied to the whole image.

Just in case it made a difference, I tried increasing the Memory Limit to maximum, and I changed the "Interactive Rendering" setting from "Between Region Changes" to "All the Time". Changing this latter preference caused my whole computer to hang for a moment (cursor wouldn't move); when the computer started responding again the problem was still present.

The same behaviour happens seemingly regardless of file type or size.

Strangely, as a work-around, tapping either Ctrl key causes the screen to redraw and everything appears to render correctly (until I make the next adjustment, that is).

### Platform
Microsoft Surface Pro (2017) with Windows 10 Pro 64 bit
LightZone_Installer_4.2.2_20210106_windows-x64 (downloaded 2021-02-20)

**Comment by RussellAult** [comment]
I just switched to my desktop (i7, Win10Pro64, same installer and download date) and this isn't a problem at all. My desktop has more memory (although the limit in LightZone is set close to the maxed-out limit on my Surface, so I don't think that's the problem). I had been running the Surface on battery; next time I'm using it I'll plug it in and see if the problem persists.

**Comment by ktgw0316** [comment]
Thank you for the detailed report. I also had this problem on m1 mac, and I think it's fixed with d0e8b62. Please wait for next release.

**Comment by RussellAult** [comment]
@ktgw0316 Great! Thanks!

**Comment by RussellAult** [comment]
Just as an update (in case it matters) plugged-in vs. battery and changing power settings made no difference.

I also just thought of another difference between my Surface and my desktop: the Surface has a high-DPI screen (with scaling), while the desktop does not.

**Comment by mrelwood** [comment]
I have the same issue on a 2019 MacBook Pro 16" running MacOS Big Sur 11.3.2. Waiting for the next release!

**Comment by ktgw0316** [comment]
I think this issue was resolved in v4.2.4.  Feel free to reopen if it still occurs.
