### ISSUE TITLE
LZ 4.2.2: Colour picker picks colour from wrong location

### ISSUE THREAD

**Issue by mrelwood** [Aries85/LightZone#256]
Lightzone 4.2.2 introduced a new issue to me, where the colour picker doesn't pick the color from the mouse cursor, but some other location of the image. At 1:1 zoom level on an 1280 x 960 image (1792 x 1120 display), the colour picker acts as if the image was positioned somewhere at the bottom right corner of the image window. Same image at "Fit" zoom level acts if the image was positioned somewhere at the bottom right corner of the whole display (or the application window).

I'm sometimes able to find the correct colour by clicking at various positions and trying to get a mental image where at the actual image the picker is positioned. But it is absolutely futile for precise colour picking.

LightZone 4.2.2
MacBook Pro 16" 2019
MacOS Big Sur 11.3.2

**Comment by ktgw0316** [comment]
Thanks for the report. I'll take a look.

**Comment by ktgw0316** [comment]
This issue was fixed in 4.2.3, but I forgot to close it.
