### ISSUE TITLE
Raspberry pi can't install most recent lightzone 

### ISSUE THREAD

**Issue by dabateman** [Aries85/LightZone#257]
Hello,
I get the following error:
The following packages have unmet dependencies:
 lightzone : Depends: libjiconfont-google-material-design-icons-java but it is not installable
             Depends: librefuel-java but it is not installable
E: Unable to correct problems, you have held broken packages.

Hope this can be resoloved as would like to have Lightzone on the Pi.

**Comment by ktgw0316** [comment]
Those two packages are available on this PPA: https://launchpad.net/~lightzone-team/+archive/ubuntu/lightzone/+packages

Which OS version are you using?  Could you show me the output of `cat /etc/lsb-release` and `uname -a` ?

**Comment by dabateman** [comment]
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
This was my result for your question.  I am not on the ubuntu version for Pi.

**Comment by dabateman** [comment]
Your link may have fixed it. I manually installed libjiconfont-google-material-design-icon-java.deb and librefuel-java.deb and the lightzone install was able to run in the terminal.

I now have to see if it will run. Crashed on first attempt to run. But its installed.

**Comment by ktgw0316** [comment]
@dabateman OK, so you are using Rasberry Pi OS 10 (formerly know as Raspbian 10), right?

I added the two lib*-java packages for Debian 10, testing, unstable and Raspbian 10 on the same OBS repository as the lightzone package today. I guess you already installed LZ via that repository, but if it is not the case, please uninstall the LZ and the two lib*-java.deb packages, then follow the instruction below to reinstall the three packages.

https://software.opensuse.org/download/package?package=lightzone&project=home:ktgw0316:LightZone
