### ISSUE TITLE
LightZone 4.2.3 VERY SLOW with max system resource utilization?

### ISSUE THREAD

**Issue by sattvakarma** [Aries85/LightZone#258]
The latest update to LZ, version 4.2.3 is running REALLY SLOW when i open an image for editing...and system resources get maxed out under Windows 10 x64, version 20H2 on a Dell Optiplex 3020 with 16 Gb RAM and a 512 Gb SSD drive.

I have moved back to LZ 4.2.2, which is working fine for me.

I wanted to post this on the forum, BUT i have not been able to login for over a year now...some problems with the http://lightzoneproject.org website as well.

**Comment by halfdave** [comment]
I have noticed this on 4.2.3 also Win10 x64 Intel Nuc i7 8th gen, 16gb ram, ssd
Seems to be related to RAM usage

1. open program
2. browse for images
3. (everything is normal)
4. open an image in the editor ( i can use a jpg or an sony arw)
3. RAM usage climbs until all RAM is used
4. Go back go browse
5. RAM is released.

**Comment by da77a** [comment]
As for @halfdave but on a system with only 4GB of RAM step 6 is "lightzone terminates after using about 2GB of RAM". 

And it is now October. Does anyone in the project actually monitor / respond to these issues? At least a notice NOT to install 4.2.3 for Windows / revert to 4.2.2 would be in order.

**Comment by andrewk8** [comment]
> I have noticed this on 4.2.3 also Win10 x64 Intel Nuc i7 8th gen, 16gb ram, ssd Seems to be related to RAM usage
> 
> 1. open program
> 2. browse for images
> 3. (everything is normal)
> 4. open an image in the editor ( i can use a jpg or an sony arw)
> 5. RAM usage climbs until all RAM is used
> 6. Go back go browse
> 7. RAM is released.

Yes. Same issue. 4.2.3. Two different computers.  Windows 10 x64 21H1 and 20H2.

Browse mode, Commit size is ~1 GB.  Switch to Edit mode on a small JPG (1600x1067), CPU usage is constant and Commit size kept growing to 17 GB.  Switch back to Browse mode and memory is released and CPU usage drops.

**Comment by sattvakarma** [comment]
has this problem been resolved? and there is no update/activity on the LZ website/forums? hope all is well.

**Comment by ktgw0316** [comment]
I believe this issue was recently fixed (391bd34), but "Lack of tile" artifacts is occurred again on macOS by that commit, so I had to workaround it too (d88f659).

I'll release v4.2.4 as soon as possible.
