### ISSUE TITLE
LZ download links? official website down?

### ISSUE THREAD

**Issue by sattvakarma** [Aries85/LightZone#264]
hello,

where can i download the latest version of LightZone? i cannot find the links on Github here?

and the website at www.lightzoneproject.org is not up for quite a bit of time...months if i recollect right. 

any updates on the above will be appreciated. 

best regards.

**Comment by jedd** [comment]
Howdi,

Head to https://github.com/ktgw0316/LightZone

On the right hand side, half way down, you'll find the Releases section - currently the latest is v4.2.4

You can click on that to get instructions and links to assets for various distros.

**Comment by ktgw0316** [comment]
Hi,

I've just added a link for download page in '[Installing](https://github.com/Aries85/LightZone#installing)' section of the README.md.

**Comment by sattvakarma** [comment]
Thank you jedd and ktgw0316!
